# `MGnipy` and `ABaCo` demo: fetching and integrating studies from MGnify API

In [1]:
# ignore debugging warning
import logging
logging.basicConfig(level=logging.WARNING)
# import packages
from mgnipy import MGnipy

In [9]:
MG = MGnipy()

studies = MG.studies(
    search="colorectal cancer"
)

studies.bulk_fetch()

studies.enrich_details()

studies.to_df(expand_nested_dicts=True)

Retrieving list_mgnify_studies pages: 100%|██████████| 1/1 [00:00<00:00,  4.82it/s]
Enriching study details: 100%|██████████| 16/16 [00:05<00:00,  2.97it/s]

,accession,ena_accessions,title,updated_at,biome__biome_name,biome__lineage
0,MGYS00010342,"[ERP180546, PRJEB98119]",Metagenome assembly of PRJNA531273 data set (A...,2026-04-21T08:55:57.306000+00:00,Intestine,root:Host-associated:Human:Digestive system:In...
1,MGYS00010413,"[PRJEB108573, ERP189408]",Metagenome assembly of PRJNA763023 data set (D...,2026-05-08T10:16:41.967000+00:00,Intestine,root:Host-associated:Human:Digestive system:In...
2,MGYS00005815,"[ERP125543, PRJEB41718]",EMG produced TPA metagenomics assembly of PRJE...,2026-05-28T15:46:58.051000+00:00,Fecal,root:Host-associated:Mammals:Digestive system:...
3,MGYS00010351,[PRJEB98880],Metagenome assembly of PRJEB27928 data set (Me...,2026-05-28T15:46:48.380000+00:00,Intestine,root:Host-associated:Human:Digestive system:In...
4,MGYS00010335,"[SRP191395, PRJNA531273]","Association of Flavonifractor plautii, a flavo...",2026-05-28T15:46:48.409000+00:00,Intestine,root:Host-associated:Human:Digestive system:In...
5,MGYS00010339,"[PRJEB27928, ERP110064]",Meta-analysis of fecal metagenomes reveals glo...,2026-05-28T15:46:48.585000+00:00,Intestine,root:Host-associated:Human:Digestive system:In...
6,MGYS00010341,"[SRP128485, PRJNA429097]",Microbiota Research on Chinses Colorectal Cancer,2026-05-28T15:46:48.645000+00:00,Intestine,root:Host-associated:Human:Digestive system:In...
7,MGYS00010348,"[ERP181024, PRJEB98642]",Metagenome assembly of PRJNA429097 data set (M...,2026-05-28T15:46:48.686000+00:00,Intestine,root:Host-associated:Human:Digestive system:In...
8,MGYS00010403,"[SRP336949, PRJNA763023]",Dysbiosis of human gut microbiome in young-ons...,2026-05-28T15:46:48.809000+00:00,Intestine,root:Host-associated:Human:Digestive system:In...
9,MGYS00002415,"[ERP106599, PRJEB24748]",EMG produced TPA metagenomics assembly of the ...,2026-05-28T15:46:52.853000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
10,MGYS00002417,"[ERP106618, PRJEB24766]",EMG produced TPA metagenomics assembly of the ...,2026-05-28T15:46:52.869000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
11,MGYS00005190,"[SRP136041, PRJNA396815]",An optimized model for screening colorectal ca...,2026-05-28T15:46:57.107000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
12,MGYS00005133,"[SRP137015, PRJNA445346]",16S rRNA gene amplicon sequencing of patients ...,2026-05-28T15:47:00.193000+00:00,Digestive system,root:Host-associated:Human:Digestive system
13,MGYS00005628,"[ERP005534, PRJEB6070]",Potential of fecal microbiota for early stage ...,2026-05-28T15:47:01.118000+00:00,Digestive system,root:Host-associated:Human:Digestive system
14,MGYS00006553,"[ERP152995, PRJEB67980]",EMG produced TPA metagenomics assembly of PRJE...,2026-05-28T15:47:01.924000+00:00,Fecal,root:Host-associated:Human:Digestive system:La...
15,MGYS00006401,"[SRP366970, PRJNA821992]",Colonization of Stenotrophomonas and its assoc...,2026-05-28T15:47:02.034000+00:00,Human,root:Host-associated:Human

In [11]:
MZ = studies.datasets

print(MZ)

MZ.downloads_df()

MGazine containing:
- MGnify pipeline versions: ['v4_1', 'v5', 'v6']
- Number of downloads: 44
- Short descriptions: ['Complete GO annotation',
 'GO slim annotation',
 'InterPro matches',
 'Phylum level taxonomies LSU',
 'Phylum level taxonomies SSU',
 'Summary of the GO annotations.',
 'Summary of the GO slim annotations.',
 'Summary of the InterPro matches.',
 'Summary of the KEGG Orthology annotations.',
 'Summary of the KEGG modules.',
 'Summary of the Pfam protein families.',
 'Summary of the antiSMASH biosynthetic gene clusters.',
 'Summary of the taxonomic assignments.',
 'Taxonomic assignments LSU',
 'Taxonomic assignments SSU']

,file_type,download_type,short_description,long_description,alias,download_group,file_size_bytes,index_files,url,accession,pipeline_version
0,tsv,Functional analysis,Summary of the antiSMASH biosynthetic gene clu...,Summary of the antiSMASH biosynthetic gene clu...,ERP180546_antismash_study_summary.tsv,study_summary.v6.assembly.antismash,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00010342,v6
1,tsv,Functional analysis,Summary of the GO annotations.,Summary of the GO annotations across all assem...,ERP180546_go_study_summary.tsv,study_summary.v6.assembly.go,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00010342,v6
2,tsv,Taxonomic analysis,Summary of the taxonomic assignments.,Summary of the taxonomic assignments across al...,ERP180546_taxonomy_study_summary.tsv,study_summary.v6.assembly.taxonomy,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00010342,v6
3,tsv,Functional analysis,Summary of the GO slim annotations.,Summary of the GO slim annotations across all ...,ERP180546_goslim_study_summary.tsv,study_summary.v6.assembly.goslim,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00010342,v6
4,tsv,Functional analysis,Summary of the KEGG modules.,Summary of the KEGG modules across all assembl...,ERP180546_kegg_modules_study_summary.tsv,study_summary.v6.assembly.kegg_modules,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00010342,v6
5,tsv,Functional analysis,Summary of the KEGG Orthology annotations.,Summary of the KEGG Orthology annotations acro...,ERP180546_ko_study_summary.tsv,study_summary.v6.assembly.ko,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00010342,v6
6,tsv,Functional analysis,Summary of the Pfam protein families.,Summary of the Pfam protein families across al...,ERP180546_pfam_study_summary.tsv,study_summary.v6.assembly.pfam,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00010342,v6
7,tsv,Functional analysis,Summary of the InterPro matches.,Summary of the InterPro matches across all ass...,ERP180546_interpro_study_summary.tsv,study_summary.v6.assembly.interpro,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00010342,v6
8,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP106599_taxonomy_abundances_SSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002415,v4_1
9,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP106599_phylum_taxonomy_abundances_SSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002415,v4_1
10,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP106599_taxonomy_abundances_LSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002415,v4_1
11,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP106599_phylum_taxonomy_abundances_LSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002415,v4_1
12,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP106599_IPR_abundances_v4.1.tsv,study_summary.v4.1.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002415,v4_1
13,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP106599_GO-slim_abundances_v4.1.tsv,study_summary.v4.1.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002415,v4_1
14,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP106599_GO_abundances_v4.1.tsv,study_summary.v4.1.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002415,v4_1
15,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP106618_taxonomy_abundances_SSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002417,v4_1
16,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP106618_phylum_taxonomy_abundances_SSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002417,v4_1
17,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP106618_taxonomy_abundances_LSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002417,v4_1
18,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP106618_phylum_taxonomy_abundances_LSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002417,v4_1
19,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP106618_IPR_abundances_v4.1.tsv,study_summary.v4.1.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002417,v4_1
20,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP106618_GO-slim_abundances_v4.1.tsv,study_summary.v4.1.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002417,v4_1
21,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP106618_GO_abundances_v4.1.tsv,study_summary.v4.1.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002417,v4_1
22,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),SRP136041_phylum_taxonomy_abundances_SSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005190,v4_1
23,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),SRP136041_taxonomy_abundances_SSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005190,v4_1
24,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),SRP137015_phylum_taxonomy_abundances_SSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005133,v4_1
25,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),SRP137015_taxonomy_abundances_SSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005133,v4_1
26,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),SRP137015_phylum_taxonomy_abundances_LSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005133,v4_1
27,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),SRP137015_taxonomy_abundances_LSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005133,v4_1
28,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP005534_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005628,v5
29,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP005534_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005628,v5
30,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP005534_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005628,v5
31,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP005534_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005628,v5
32,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP005534_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005628,v5
33,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP005534_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005628,v5
34,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP005534_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005628,v5
35,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP152995_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006553,v5
36,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP152995_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006553,v5
37,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP152995_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006553,v5
38,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP152995_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006553,v5
39,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP152995_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006553,v5
40,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP152995_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006553,v5
41,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP152995_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006553,v5
42,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),SRP366970_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006401,v5
43,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),SRP366970_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006401,v5

In [13]:
ssu = MZ["Taxonomic assignments SSU"]

print(type(ssu))
print(ssu)

ssu.downloads_df()

WARNING:mgnipy.V2.datasets.taxonomic:Multiple pipeline versions detected -- MGazine methods may not work as expected.

MGazine Curation TaxaMGazine containing:
- MGnify pipeline versions: ['v4_1', 'v5']
- Number of downloads: 7
- Short descriptions: ['Taxonomic assignments SSU']
-----------------------
Next steps: Use `.load()` to initialize.

<class 'mgnipy.V2.datasets.taxonomic.TaxaMGazine'>
MGazine Curation TaxaMGazine containing:
- MGnify pipeline versions: ['v4_1', 'v5']
- Number of downloads: 7
- Short descriptions: ['Taxonomic assignments SSU']

,file_type,download_type,short_description,long_description,alias,download_group,file_size_bytes,index_files,url,accession,pipeline_version
0,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP106599_taxonomy_abundances_SSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002415,v4_1
1,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP106618_taxonomy_abundances_SSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00002417,v4_1
2,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),SRP136041_taxonomy_abundances_SSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005190,v4_1
3,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),SRP137015_taxonomy_abundances_SSU_v4.1.tsv,study_summary.v4.1.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005133,v4_1
4,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP005534_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00005628,v5
5,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP152995_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006553,v5
6,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),SRP366970_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006401,v5

In [15]:
ssu.load()

ssu.to_pandas()

TaxaMGazine loaded with 7 datasets.
Cached runs results: 0 of total 3220.

,taxonomy,OGWQ01,OGWR01,OGWS01,OGWT01,OGWU01,OGWV01,OGWW01,OGWX01,OGWY01,...,SRR18568035,SRR18568045,SRR18568036,SRR18568046,SRR18568037,SRR18568047,SRR18568038,SRR18568048,SRR18568039,SRR18568049
0,sk__Archaea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,sk__Archaea;k__;p__Crenarchaeota,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,sk__Archaea;k__;p__Euryarchaeota,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,sk__Archaea;k__;p__Euryarchaeota;c__Methanobac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,sk__Archaea;k__;p__Euryarchaeota;c__Methanobac...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3476,sk__Bacteria;k__;p__Proteobacteria;c__Gammapro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0
3477,sk__Bacteria;k__;p__Proteobacteria;c__Alphapro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3478,sk__Bacteria;k__;p__Proteobacteria;c__Betaprot...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3479,sk__Bacteria;k__;p__Actinobacteria;c__Thermole...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
3480,sk__Bacteria;k__;p__Proteobacteria;c__Betaprot...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
ssu.enrich_runs()

Enriching runs:   0%|          | 0/3220 [00:00<?, ?it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGWQ01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 1/3220 [00:00<25:46,  2.08it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGWR01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 2/3220 [00:00<24:36,  2.18it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGWS01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 3/3220 [00:01<24:25,  2.19it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGWT01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 4/3220 [00:01<24:12,  2.21it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGWU01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 5/3220 [00:02<24:12,  2.21it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGWV01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 6/3220 [00:02<24:06,  2.22it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGWW01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 7/3220 [00:03<24:12,  2.21it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGWX01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 8/3220 [00:03<24:13,  2.21it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGWY01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 9/3220 [00:04<24:14,  2.21it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGWZ01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 10/3220 [00:04<24:18,  2.20it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXA01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 11/3220 [00:05<24:24,  2.19it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXB01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 12/3220 [00:05<24:20,  2.20it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXC01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 13/3220 [00:05<24:15,  2.20it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXD01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 14/3220 [00:06<24:23,  2.19it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXE01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 15/3220 [00:06<24:23,  2.19it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXF01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   0%|          | 16/3220 [00:07<24:22,  2.19it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXG01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 17/3220 [00:07<24:25,  2.19it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXH01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 18/3220 [00:08<24:39,  2.16it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXI01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 19/3220 [00:08<24:28,  2.18it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXJ01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 20/3220 [00:09<24:21,  2.19it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXK01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 21/3220 [00:09<24:25,  2.18it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXL01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 22/3220 [00:10<24:28,  2.18it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXM01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 23/3220 [00:10<24:39,  2.16it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXN01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 24/3220 [00:10<24:40,  2.16it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXO01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 25/3220 [00:11<24:52,  2.14it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXP01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 26/3220 [00:11<24:47,  2.15it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXQ01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 27/3220 [00:12<24:42,  2.15it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXR01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 28/3220 [00:12<24:46,  2.15it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXS01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 29/3220 [00:13<24:55,  2.13it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXT01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 30/3220 [00:13<24:50,  2.14it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXU01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 31/3220 [00:14<24:40,  2.15it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXV01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 32/3220 [00:14<24:46,  2.14it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXW01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 33/3220 [00:15<24:34,  2.16it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXX01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 34/3220 [00:15<24:40,  2.15it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXY01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 35/3220 [00:16<24:31,  2.16it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGXZ01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 36/3220 [00:16<24:36,  2.16it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYA01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 37/3220 [00:17<24:35,  2.16it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYB01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 38/3220 [00:17<24:40,  2.15it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYC01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 39/3220 [00:17<24:35,  2.16it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYD01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|          | 40/3220 [00:18<24:44,  2.14it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYE01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|▏         | 41/3220 [00:18<24:45,  2.14it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYF01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|▏         | 42/3220 [00:19<24:40,  2.15it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYG01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|▏         | 43/3220 [00:19<24:52,  2.13it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYH01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|▏         | 44/3220 [00:20<24:36,  2.15it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYI01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|▏         | 45/3220 [00:20<24:46,  2.14it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYJ01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|▏         | 46/3220 [00:21<24:34,  2.15it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYK01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|▏         | 47/3220 [00:21<24:51,  2.13it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYL01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   1%|▏         | 48/3220 [00:22<24:35,  2.15it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYM01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
Enriching runs:   2%|▏         | 49/3220 [00:22<24:45,  2.13it/s]ERROR:mgnipy.V2.query_executor:Error fetching request num 1: Resource not found: The requested file does not exist. Please check the endpoint and parameters.
ERROR:mgnipy.V2.datasets.taxonomic:Error occurred while enriching run OGYN01: Resource not found: The requested file does not exist. Please check the endpoint and parameters.

In [21]:
adata=ssu.to_anndata()

/home/s243564/miniforge3/envs/abaco/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)
ERROR:mgnipy.V2.datasets.taxonomic:Returning without metadata() as var - Error occurred while converting to AnnData: Observations annot. `var` must have as many rows as `X` has columns (3220), but has 200 rows.
/home/s243564/miniforge3/envs/abaco/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [24]:
adata.X

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ...,  0.,  0.,  0.],
       [nan, nan, nan, ...,  0.,  0.,  0.],
       [nan, nan, nan, ...,  0.,  0.,  0.]], shape=(3481, 3220))